name: bulk_rna_seq
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # --- Python stack ---
  - python=3.11
  - numpy
  - pandas
  - pip
  - tqdm
  - sra-tools
  - kallisto
  - fastp
  - multiqc
  - click
  - matplotlib
  - pyarrow          

  # --- R / Bioconductor stack ---
  - r-base>=4.3,<4.4
  - r-optparse
  - r-readr
  - r-dplyr
  - r-tibble
  - r-tidyr
  - r-ggplot2
  - r-data.table     
  - r-circlize

  # Bioconductor packages
  - bioconductor-deseq2
  - bioconductor-tximport
  - bioconductor-complexheatmap
  - bioconductor-egad 
